/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */
package parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TYPE = 5;
  /** RegularExpression Id. */
  int MACRO = 6;
  /** RegularExpression Id. */
  int ATRIB = 7;
  /** RegularExpression Id. */
  int TYPE_ESCOLHIDO = 8;
  /** RegularExpression Id. */
  int DESCRITOR = 9;
  /** RegularExpression Id. */
  int VIRG = 10;
  /** RegularExpression Id. */
  int PONTUACAO = 11;
  /** RegularExpression Id. */
  int LASTNAME = 12;
  /** RegularExpression Id. */
  int UPPERCASE = 13;
  /** RegularExpression Id. */
  int CAPITALIZED = 14;
  /** RegularExpression Id. */
  int DATA = 15;
  /** RegularExpression Id. */
  int PROP = 16;
  /** RegularExpression Id. */
  int ENDLINE = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"type\"",
    "\"macro\"",
    "\":\"",
    "\"Artigo\"",
    "<DESCRITOR>",
    "\",\"",
    "<PONTUACAO>",
    "\"lastName\"",
    "\"uppercase\"",
    "\"capitalized\"",
    "\"dd/mm/yyyy\"",
    "<PROP>",
    "\"$\"",
  };

}
